services:
  budtragetapi:
    image: budtragetapi-compose
    container_name: budtraget-compose-dev  # Ensures the container is always named this
    build:
      context: .
      dockerfile: Budtraget.Api/Dockerfile.debug
      args:
        - configuration=Debug
    ports:
      - 5126:5126 # App port (still exposed, just not auto-started)
      - 5005:5005  # Debugging port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_MODIFIABLE_ASSEMBLIES=debug
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
      - ASPNETCORE_URLS=http://+:5126
    volumes:
      #- ~/.vsdbg:/remote_debugger:rw
      #- ./Budtraget.Api:/src/Budtraget.Api:cached  # Optional: only if hot reload or code sync needed
      - ./Budtraget.Api:/src/Budtraget.Api:cached
    # command: ["dotnet", "Budtraget.Api.dll", "--server.urls", "http://+:5126"]