version: '3.4'

services:
  mywebapi:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    ports:
      - "8080:8080"
      - "9229:9229" # Debugging port
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages
    command: ["dotnet", "Budtraget.dll", "--no-launch-profile", "--no-build"]