services:
  budtragetapi:
    image: budtragetapi-release
    container_name: budtraget-compose-release
    build:
      context: .
      dockerfile: Budtraget.Api/Dockerfile.release
      args:
        - configuration=Release
    ports:
      - 80:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080